# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SegmentControllerDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'STPopup'
pod 'EasyTransition', '~> 2.0'
pod 'SDWebImage', '~> 4.0'
pod 'IQKeyboardManagerSwift', '~> 5.0.0'
pod 'AlamofireSwiftyJSON'



  # Pods for SegmentControllerDemo
  
  target 'SegmentControllerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
